
services:

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-1.c5gqasca0khp.eu-west-3.rds.amazonaws.com:5432/myappdb
      - SPRING_DATASOURCE_USERNAME=myappdb
      - SPRING_DATASOURCE_PASSWORD=1234567890
      - SERVER_PORT=5000

  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
