services:

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}

  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
