services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myappdbv2.crwa0y4usk7a.eu-west-1.rds.amazonaws.com:5432/myappdbv2
      - SPRING_DATASOURCE_USERNAME=myappuser
      - SPRING_DATASOURCE_PASSWORD=1234567890
      - SERVER_PORT=5000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
          - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=myappdbv2
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=1234567890
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
