branch-defaults:
  default:
    environment: legistrack-env
    group_suffix: null
environment-defaults:
  legistrack-env:
    branch: null
    repository: null
global:
  application_name: LegisTrack
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 21
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
