services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: bankingapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./BankingApp.API
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=bankingapp;Username=postgres;Password=${DB_PASSWORD}"
      JwtSettings__Secret: ${JWT_SECRET}
      JwtSettings__Issuer: ${JWT_ISSUER}
      JwtSettings__Audience: ${JWT_AUDIENCE}
      Seeder__AdminPassword: ${ADMIN_PASSWORD}
    ports:
      - "8080:8080"

  web:
    build: ./BankingApp.Web
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  postgres_data:
